/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculusjeopardy;

import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class MainJeopardyUI extends javax.swing.JFrame {

    /**
     * Creates new form MainJeopardyUI
     */
    public MainJeopardyUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categories = new javax.swing.JPanel();
        derivativesLabel = new javax.swing.JLabel();
        integralsLabel = new javax.swing.JLabel();
        relativeExtremaLabel = new javax.swing.JLabel();
        concavityLabel = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        derivatives200 = new javax.swing.JLabel();
        integrals200 = new javax.swing.JLabel();
        relativeExtrema200 = new javax.swing.JLabel();
        concavity200 = new javax.swing.JLabel();
        derivatives400 = new javax.swing.JLabel();
        integrals400 = new javax.swing.JLabel();
        relativeExtrema400 = new javax.swing.JLabel();
        concavity400 = new javax.swing.JLabel();
        derivatives600 = new javax.swing.JLabel();
        integrals600 = new javax.swing.JLabel();
        relativeExtrema600 = new javax.swing.JLabel();
        concavity600 = new javax.swing.JLabel();
        derivatives800 = new javax.swing.JLabel();
        integrals800 = new javax.swing.JLabel();
        relativeExtrema800 = new javax.swing.JLabel();
        concavity800 = new javax.swing.JLabel();
        derivatives1000 = new javax.swing.JLabel();
        integrals1000 = new javax.swing.JLabel();
        relativeExtrema1000 = new javax.swing.JLabel();
        concavity1000 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 628));

        categories.setBackground(new java.awt.Color(0, 0, 0));
        categories.setMaximumSize(new java.awt.Dimension(300, 32767));
        categories.setLayout(new java.awt.GridLayout(1, 4, 10, 10));

        derivativesLabel.setBackground(new java.awt.Color(6, 12, 233));
        derivativesLabel.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        derivativesLabel.setForeground(new java.awt.Color(255, 255, 255));
        derivativesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        derivativesLabel.setText("<html><center>DERIVATIVES</center></html>");
        derivativesLabel.setOpaque(true);
        categories.add(derivativesLabel);

        integralsLabel.setBackground(new java.awt.Color(6, 12, 233));
        integralsLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        integralsLabel.setForeground(new java.awt.Color(255, 255, 255));
        integralsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        integralsLabel.setText("<html><center>INTEGRALS</center></html>");
        integralsLabel.setOpaque(true);
        categories.add(integralsLabel);

        relativeExtremaLabel.setBackground(new java.awt.Color(6, 12, 233));
        relativeExtremaLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        relativeExtremaLabel.setForeground(new java.awt.Color(255, 255, 255));
        relativeExtremaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        relativeExtremaLabel.setText("<html><center>RELATIVE<br>EXTREMA</center></html>");
        relativeExtremaLabel.setOpaque(true);
        categories.add(relativeExtremaLabel);

        concavityLabel.setBackground(new java.awt.Color(6, 12, 233));
        concavityLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        concavityLabel.setForeground(new java.awt.Color(255, 255, 255));
        concavityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        concavityLabel.setText("<html><center>CONCAVITY</center></html>");
        concavityLabel.setOpaque(true);
        categories.add(concavityLabel);

        container.setBackground(new java.awt.Color(0, 0, 0));
        container.setLayout(new java.awt.GridLayout(5, 4, 10, 10));

        derivatives200.setBackground(new java.awt.Color(6, 12, 233));
        derivatives200.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        derivatives200.setForeground(new java.awt.Color(255, 204, 0));
        derivatives200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        derivatives200.setText("<html><span style=\"font-family: impact;\">$200</span></html>");
        derivatives200.setOpaque(true);
        derivatives200.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                derivatives200MouseClicked(evt);
            }
        });
        container.add(derivatives200);

        integrals200.setBackground(new java.awt.Color(6, 12, 233));
        integrals200.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        integrals200.setForeground(new java.awt.Color(255, 204, 0));
        integrals200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        integrals200.setText("<html><span style=\"font-family: impact;\">$200</span></html>");
        integrals200.setOpaque(true);
        integrals200.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                integrals200MouseClicked(evt);
            }
        });
        container.add(integrals200);

        relativeExtrema200.setBackground(new java.awt.Color(6, 12, 233));
        relativeExtrema200.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        relativeExtrema200.setForeground(new java.awt.Color(255, 204, 0));
        relativeExtrema200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        relativeExtrema200.setText("<html><span style=\"font-family: impact;\">$200</span></html>");
        relativeExtrema200.setOpaque(true);
        container.add(relativeExtrema200);

        concavity200.setBackground(new java.awt.Color(6, 12, 233));
        concavity200.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        concavity200.setForeground(new java.awt.Color(255, 204, 0));
        concavity200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        concavity200.setText("<html><span style=\"font-family: impact;\">$200</span></html>");
        concavity200.setOpaque(true);
        container.add(concavity200);

        derivatives400.setBackground(new java.awt.Color(6, 12, 233));
        derivatives400.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        derivatives400.setForeground(new java.awt.Color(255, 204, 0));
        derivatives400.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        derivatives400.setText("<html><span style=\"font-family: impact;\">$400</span></html>");
        derivatives400.setOpaque(true);
        container.add(derivatives400);

        integrals400.setBackground(new java.awt.Color(6, 12, 233));
        integrals400.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        integrals400.setForeground(new java.awt.Color(255, 204, 0));
        integrals400.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        integrals400.setText("<html><span style=\"font-family: impact;\">$400</span></html>");
        integrals400.setOpaque(true);
        container.add(integrals400);

        relativeExtrema400.setBackground(new java.awt.Color(6, 12, 233));
        relativeExtrema400.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        relativeExtrema400.setForeground(new java.awt.Color(255, 204, 0));
        relativeExtrema400.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        relativeExtrema400.setText("<html><span style=\"font-family: impact;\">$400</span></html>");
        relativeExtrema400.setOpaque(true);
        container.add(relativeExtrema400);

        concavity400.setBackground(new java.awt.Color(6, 12, 233));
        concavity400.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        concavity400.setForeground(new java.awt.Color(255, 204, 0));
        concavity400.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        concavity400.setText("<html><span style=\"font-family: impact;\">$400</span></html>");
        concavity400.setOpaque(true);
        container.add(concavity400);

        derivatives600.setBackground(new java.awt.Color(6, 12, 233));
        derivatives600.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        derivatives600.setForeground(new java.awt.Color(255, 204, 0));
        derivatives600.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        derivatives600.setText("<html><span style=\"font-family: impact;\">$600</span></html>");
        derivatives600.setOpaque(true);
        container.add(derivatives600);

        integrals600.setBackground(new java.awt.Color(6, 12, 233));
        integrals600.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        integrals600.setForeground(new java.awt.Color(255, 204, 0));
        integrals600.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        integrals600.setText("<html><span style=\"font-family: impact;\">$600</span></html>");
        integrals600.setOpaque(true);
        container.add(integrals600);

        relativeExtrema600.setBackground(new java.awt.Color(6, 12, 233));
        relativeExtrema600.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        relativeExtrema600.setForeground(new java.awt.Color(255, 204, 0));
        relativeExtrema600.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        relativeExtrema600.setText("<html><span style=\"font-family: impact;\">$600</span></html>");
        relativeExtrema600.setOpaque(true);
        container.add(relativeExtrema600);

        concavity600.setBackground(new java.awt.Color(6, 12, 233));
        concavity600.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        concavity600.setForeground(new java.awt.Color(255, 204, 0));
        concavity600.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        concavity600.setText("<html><span style=\"font-family: impact;\">$600</span></html>");
        concavity600.setOpaque(true);
        container.add(concavity600);

        derivatives800.setBackground(new java.awt.Color(6, 12, 233));
        derivatives800.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        derivatives800.setForeground(new java.awt.Color(255, 204, 0));
        derivatives800.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        derivatives800.setText("<html><span style=\"font-family: impact;\">$800</span></html>");
        derivatives800.setOpaque(true);
        container.add(derivatives800);

        integrals800.setBackground(new java.awt.Color(6, 12, 233));
        integrals800.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        integrals800.setForeground(new java.awt.Color(255, 204, 0));
        integrals800.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        integrals800.setText("<html><span style=\"font-family: impact;\">$800</span></html>");
        integrals800.setOpaque(true);
        container.add(integrals800);

        relativeExtrema800.setBackground(new java.awt.Color(6, 12, 233));
        relativeExtrema800.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        relativeExtrema800.setForeground(new java.awt.Color(255, 204, 0));
        relativeExtrema800.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        relativeExtrema800.setText("<html><span style=\"font-family: impact;\">$800</span></html>");
        relativeExtrema800.setOpaque(true);
        container.add(relativeExtrema800);

        concavity800.setBackground(new java.awt.Color(6, 12, 233));
        concavity800.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        concavity800.setForeground(new java.awt.Color(255, 204, 0));
        concavity800.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        concavity800.setText("<html><span style=\"font-family: impact;\">$800</span></html>");
        concavity800.setOpaque(true);
        container.add(concavity800);

        derivatives1000.setBackground(new java.awt.Color(6, 12, 233));
        derivatives1000.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        derivatives1000.setForeground(new java.awt.Color(255, 204, 0));
        derivatives1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        derivatives1000.setText("<html><span style=\"font-family: impact;\">$1000</span></html>");
        derivatives1000.setOpaque(true);
        container.add(derivatives1000);

        integrals1000.setBackground(new java.awt.Color(6, 12, 233));
        integrals1000.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        integrals1000.setForeground(new java.awt.Color(255, 204, 0));
        integrals1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        integrals1000.setText("<html><span style=\"font-family: impact;\">$1000</span></html>");
        integrals1000.setOpaque(true);
        container.add(integrals1000);

        relativeExtrema1000.setBackground(new java.awt.Color(6, 12, 233));
        relativeExtrema1000.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        relativeExtrema1000.setForeground(new java.awt.Color(255, 204, 0));
        relativeExtrema1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        relativeExtrema1000.setText("<html><span style=\"font-family: impact;\">$1000</span></html>");
        relativeExtrema1000.setOpaque(true);
        container.add(relativeExtrema1000);

        concavity1000.setBackground(new java.awt.Color(6, 12, 233));
        concavity1000.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        concavity1000.setForeground(new java.awt.Color(255, 204, 0));
        concavity1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        concavity1000.setText("<html><span style=\"font-family: impact;\">$1000</span></html>");
        concavity1000.setOpaque(true);
        container.add(concavity1000);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categories, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
                    .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categories, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void derivatives200MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derivatives200MouseClicked
        // TODO add your handling code here:
        if(!derivatives200.getText().equals("")) {
            derivatives200.setText("");
            displayQuestion(0, 0);
        }
    }//GEN-LAST:event_derivatives200MouseClicked

    private void integrals200MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_integrals200MouseClicked
        // TODO add your handling code here:
        if(!integrals200.getText().equals("")) {
            integrals200.setText("");
            displayQuestion(0, 1);
        }
    }//GEN-LAST:event_integrals200MouseClicked
    
    public void displayQuestion(int cost, int category) {
        CalculusJeopardy.frame2.question.setText(CalculusJeopardy.questions[cost][category]);
        CalculusJeopardy.frame2.setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJeopardyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJeopardyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJeopardyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJeopardyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJeopardyUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel categories;
    public javax.swing.JLabel concavity1000;
    public javax.swing.JLabel concavity200;
    public javax.swing.JLabel concavity400;
    public javax.swing.JLabel concavity600;
    public javax.swing.JLabel concavity800;
    public javax.swing.JLabel concavityLabel;
    public javax.swing.JPanel container;
    public javax.swing.JLabel derivatives1000;
    public javax.swing.JLabel derivatives200;
    public javax.swing.JLabel derivatives400;
    public javax.swing.JLabel derivatives600;
    public javax.swing.JLabel derivatives800;
    public javax.swing.JLabel derivativesLabel;
    public javax.swing.JLabel integrals1000;
    public javax.swing.JLabel integrals200;
    public javax.swing.JLabel integrals400;
    public javax.swing.JLabel integrals600;
    public javax.swing.JLabel integrals800;
    public javax.swing.JLabel integralsLabel;
    public javax.swing.JLabel relativeExtrema1000;
    public javax.swing.JLabel relativeExtrema200;
    public javax.swing.JLabel relativeExtrema400;
    public javax.swing.JLabel relativeExtrema600;
    public javax.swing.JLabel relativeExtrema800;
    public javax.swing.JLabel relativeExtremaLabel;
    // End of variables declaration//GEN-END:variables
}
