/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculusjeopardy;

/**
 *
 * @author root
 */
public class ScoresUI extends javax.swing.JFrame {

    /**
     * Creates new form InformationUI
     */
    public ScoresUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contestantLabel1 = new javax.swing.JLabel();
        contestantLabel2 = new javax.swing.JLabel();
        contestantLabel3 = new javax.swing.JLabel();
        scoreLabel1 = new javax.swing.JLabel();
        scoreLabel2 = new javax.swing.JLabel();
        scoreLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 3, 10, 0));

        contestantLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        contestantLabel1.setForeground(new java.awt.Color(255, 255, 255));
        contestantLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contestantLabel1.setText("Contestant #1");
        getContentPane().add(contestantLabel1);

        contestantLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        contestantLabel2.setForeground(new java.awt.Color(255, 255, 255));
        contestantLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contestantLabel2.setText("Contestant #2");
        getContentPane().add(contestantLabel2);

        contestantLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        contestantLabel3.setForeground(new java.awt.Color(255, 255, 255));
        contestantLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contestantLabel3.setText("Contestant #3");
        getContentPane().add(contestantLabel3);

        scoreLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        scoreLabel1.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel1.setText("Score #1");
        getContentPane().add(scoreLabel1);

        scoreLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        scoreLabel2.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel2.setText("Score #2");
        getContentPane().add(scoreLabel2);

        scoreLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        scoreLabel3.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel3.setText("Score #3");
        getContentPane().add(scoreLabel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoresUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoresUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoresUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoresUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoresUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel contestantLabel1;
    public javax.swing.JLabel contestantLabel2;
    public javax.swing.JLabel contestantLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel scoreLabel1;
    public javax.swing.JLabel scoreLabel2;
    public javax.swing.JLabel scoreLabel3;
    // End of variables declaration//GEN-END:variables
}
